//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDC.UnloadingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnloadingServiceReference.IUnloadingService")]
    public interface IUnloadingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnloadingService/ExportToExcel", ReplyAction="http://tempuri.org/IUnloadingService/ExportToExcelResponse")]
        void ExportToExcel(int upID, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnloadingService/ExportToExcel", ReplyAction="http://tempuri.org/IUnloadingService/ExportToExcelResponse")]
        System.Threading.Tasks.Task ExportToExcelAsync(int upID, string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnloadingServiceChannel : EDC.UnloadingServiceReference.IUnloadingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnloadingServiceClient : System.ServiceModel.ClientBase<EDC.UnloadingServiceReference.IUnloadingService>, EDC.UnloadingServiceReference.IUnloadingService {
        
        public UnloadingServiceClient() {
        }
        
        public UnloadingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnloadingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnloadingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnloadingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ExportToExcel(int upID, string userName) {
            base.Channel.ExportToExcel(upID, userName);
        }
        
        public System.Threading.Tasks.Task ExportToExcelAsync(int upID, string userName) {
            return base.Channel.ExportToExcelAsync(upID, userName);
        }
    }
}
